services:
  - type: web
    name: smart-store-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "*"
